# This configuration file sets up global settings and recognizers for entity extraction
# using custom regex-based patterns and built-in spaCy recognizers.

# Global configuration settings:
supported_languages:
  - nb                        # Supported language: Norwegian Bokmål
global_regex_flags: 26         # Global regex flags used in pattern matching

# Recognizers for extracting various entities:
recognizers:
  # Norwegian custom recognizers
  - name: NO_FODSELSNUMMER_Recognizer  # Recognizer for Norwegian social security numbers (fodselsnummer)
    supported_languages:
      - nb
    supported_entity: NO_FODSELSNUMMER
    type: custom
    patterns:
      - name: fodselsnummer_pattern
        regex: \b\d{6}\s?\d{5}\b
        score: 0.9
      - name: fodselsnummer_strict
        regex: \b[0-3]\d[0-1]\d\d\d\s?\d{5}\b
        score: 0.95

  - name: NO_PHONE_NUMBER_Recognizer   # Recognizer for Norwegian phone numbers
    supported_languages:
      - nb
    supported_entity: NO_PHONE_NUMBER
    type: custom
    patterns:
      - name: norwegian_phone_pattern
        regex: \b(?:\+47\s?)?(\d{2}\s?\d{2}\s?\d{2}\s?\d{2})\b
        score: 0.95
      - name: norwegian_phone_format_2
        regex: \b(?:\+47\s?)?(\d{3}\s?\d{2}\s?\d{3})\b
        score: 0.95

  - name: NO_ADDRESS_Recognizer          # Recognizer for Norwegian addresses
    supported_languages:
      - nb
    supported_entity: NO_ADDRESS
    type: custom
    patterns:
      - name: norwegian_address_pattern
        regex: (\b(?:[A-Za-zÆØÅæøå]+\s){1,4}\d{1,4}(?:,\s)?\d{4}\s[A-Za-zÆØÅæøå]+)|(\bPostboks\s?\d{1,5}(?:,\s)?\d{4}\s[A-Za-zÆØÅæøå]+)|(\b\d{4}\s[A-Za-zÆØÅæøå]+\b)|(\b[A-Za-zÆØÅæøå]+\s\d{1,4},?\s?\d{4}\s[A-Za-zÆØÅæøå]+\b)
        score: 0.98

  - name: NO_BANK_ACCOUNT_Recognizer     # Recognizer for Norwegian bank account numbers
    supported_languages:
      - nb
    supported_entity: NO_BANK_ACCOUNT
    type: custom
    patterns:
      - name: bank_account_pattern
        regex: \b\d{4}[.\s]?\d{2}[.\s]?\d{5}\b
        score: 0.85
      - name: bank_account_with_prefix
        regex: \b(?:kontonr\.?|kontonummer:?|bankkontonummer:?|konto:?)\s*\d{4}[.\s]?\d{2}[.\s]?\d{5}\b
        score: 0.9

  - name: NO_COMPANY_NUMBER_Recognizer    # Recognizer for Norwegian company numbers
    supported_languages:
      - nb
    supported_entity: NO_COMPANY_NUMBER
    type: custom
    patterns:
      - name: company_number_pattern
        regex: \b(?:org\.?(?:anisasjons)?nr\.?:?\s?)?\d{3}[\s]?\d{3}[\s]?\d{3}\b
        score: 0.85
      - name: company_number_with_prefix
        regex: \b(?:organisasjonsnummer|organisasjonsnr|orgnr|org\.nr\.|org\s?nr)\.?:?\s*\d{3}[\s]?\d{3}[\s]?\d{3}\b
        score: 0.9

  - name: NO_LICENSE_PLATE_Recognizer     # Recognizer for Norwegian vehicle license plates
    supported_languages:
      - nb
    supported_entity: NO_LICENSE_PLATE
    type: custom
    patterns:
      - name: license_plate_pattern
        regex: \b[A-Z]{2}[\s]?\d{4,5}\b
        score: 0.85
      - name: license_plate_with_prefix
        regex: \b(?:reg\.?(?:istrerings)?nr\.?|bilnr\.?|bilskilt:?)\s*[A-Z]{2}[\s]?\d{4,5}\b
        score: 0.9

  # Common global recognizers that work in any language:
  - name: EMAIL_ADDRESS_Recognizer        # Recognizer for email addresses
    supported_languages:
      - nb
    supported_entity: EMAIL_ADDRESS
    type: custom
    patterns:
      - name: email_pattern
        regex: \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
        score: 0.8
      - name: email_with_prefix
        regex: \b(?:e-post|epost|mail|e-mail):?\s*[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
        score: 0.9

  - name: DATE_TIME_Recognizer            # Recognizer for date and time expressions
    supported_languages:
      - nb
    supported_entity: DATE_TIME
    type: custom
    patterns:
      - name: norwegian_date_pattern
        regex: \b\d{1,2}\.\d{1,2}\.\d{4}\b
        score: 0.7
      - name: iso_date_pattern
        regex: \b\d{4}-\d{2}-\d{2}\b
        score: 0.7
      - name: norwegian_text_date
        regex: \b\d{1,2}\.?\s+(?:januar|februar|mars|april|mai|juni|juli|august|september|oktober|november|desember)\s+\d{4}\b
        score: 0.8

  - name: CRYPTO_Recognizer               # Recognizer for cryptocurrency addresses
    supported_languages:
      - nb
    supported_entity: CRYPTO
    type: custom
    patterns:
      - name: bitcoin_address
        regex: \b(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}\b
        score: 0.85
      - name: ethereum_address
        regex: \b0x[a-fA-F0-9]{40}\b
        score: 0.85

  - name: IBAN_CODE_Recognizer            # Recognizer for IBAN codes
    supported_languages:
      - nb
    supported_entity: IBAN_CODE
    type: custom
    patterns:
      - name: iban_pattern
        regex: \bNO\d{2}\s?\d{4}\s?\d{4}\s?\d{3}\b
        score: 0.9

  - name: IP_ADDRESS_Recognizer           # Recognizer for IP addresses (IPv4 and IPv6)
    supported_languages:
      - nb
    supported_entity: IP_ADDRESS
    type: custom
    patterns:
      - name: ipv4_pattern
        regex: \b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b
        score: 0.9
      - name: ipv6_simple_pattern
        regex: \b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\b
        score: 0.9

  - name: URL_Recognizer                  # Recognizer for URLs and domains
    supported_languages:
      - nb
    supported_entity: URL
    type: custom
    patterns:
      - name: url_pattern
        regex: https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+[^\s,]
        score: 0.9
      - name: domain_pattern
        regex: \b(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]\b
        score: 0.7

  - name: MEDICAL_LICENSE_Recognizer       # Recognizer for medical licenses (HPR numbers)
    supported_languages:
      - nb
    supported_entity: MEDICAL_LICENSE
    type: custom
    patterns:
      - name: norwegian_hpr_number
        regex: \bHPR-(?:\d{7}|[A-Z0-9]{9})\b
        score: 0.9

  # Built-in recognizers that leverage spaCy NLP for entity recognition:
  - name: SpacyRecognizer
    supported_languages:
      - nb
    type: predefined