# Presidio configuration for Norwegian Bokmål (nb)
# Includes tuned recognizers for PERSON,ADDRESS, PHONE, EMAIL,
# DATE/TIME and all existing Norwegian-specific patterns.

# Global configuration settings
supported_languages:
  - nb                                    # Norwegian Bokmål

# re.IGNORECASE (2) | re.UNICODE (32) = 34
global_regex_flags: 34                    # case-insensitive, Unicode-aware

# Recognizers
recognizers:

  # PERSON
  - name: PERSON_P_Recognizer
    supported_languages: [nb]
    supported_entity: PERSON_P
    type: custom
    context: ["navn", "fornavn", "etternavn"]
    patterns:
      - name: person_first_last
        regex: >-
          \b[ÆØÅA-Z][æøåa-z]+(?:-[ÆØÅA-Z][æøåa-z]+)?
          (?:\s+[ÆØÅA-Z][æøåa-z]+(?:-[ÆØÅA-Z][æøåa-z]+)?)+\b
          (?!\s+(?:gate|vei|veien|gata|veg|vegen|kommune)\b)
        score: 0.55
      - name: person_single_labeled
        regex: (?<=\b(?:navn|fornavn|etternavn)\s*:?\s*)[ÆØÅA-Z][æøåa-z]{2,}\b
        score: 0.70


  # Norwegian social-security numbers
  - name: NO_FODSELSNUMMER_P_Recognizer
    supported_languages: [nb]
    supported_entity: NO_FODSELSNUMMER_P
    type: custom
    patterns:
      - name: fodselsnummer_pattern
        regex: \b\d{6}\s?\d{5}\b
        score: 0.90
      - name: fodselsnummer_strict
        regex: \b[0-3]\d[0-1]\d\d\d\s?\d{5}\b
        score: 0.95

  # PHONE
  - name: NO_PHONE_NUMBER_P_Recognizer
    supported_languages: [nb]
    supported_entity: NO_PHONE_NUMBER_P
    type: custom
    context: ["tlf", "telefon", "mob", "mobil"]
    patterns:
      - name: norwegian_phone_flex
        regex: (?<!\d)(?:\+47|0047)?\s*(?:\d[\s\-]?){7}\d(?!\d)
        score: 0.70
      - name: norwegian_phone_plain
        regex: (?<!\d)\d{8}(?!\d)
        score: 0.50

  # ADDRESS
  - name: NO_ADDRESS_P_Recognizer
    supported_languages: [nb]
    supported_entity: NO_ADDRESS_P
    type: custom
    context: ["adresse", "poststed", "postnr", "postnummer"]
    patterns:
      - name: street_postcode_city
        regex: >-
          \b[ÆØÅA-Z][\wÆØÅæøå.\- ]+?\s+\d+\s*[A-Za-z]?
          (?:\s*[A-Za-z]\d+)?\s*,?\s*\d{4}\s+
          [A-ZÆØÅæøå][A-Za-zÆØÅæøå]*(?:\s+[A-ZÆØÅæøå][A-Za-zÆØÅæøå]*)*\b
        score: 0.90
      - name: street_and_number
        regex: >-
          \b[ÆØÅA-Z][A-Za-zÆØÅæøå.\- ]+
          (?:gate|gata|vei|veien|veg|vegen|plass|allé|alle|tun)
          \s+\d+\s*[A-Za-z]?\b
        score: 0.60

  # BANK-ACCOUNT numbers
  - name: NO_BANK_ACCOUNT_P_Recognizer
    supported_languages: [nb]
    supported_entity: NO_BANK_ACCOUNT_P
    type: custom
    patterns:
      - name: bank_account_pattern
        regex: \b\d{4}[.\s]?\d{2}[.\s]?\d{5}\b
        score: 0.85
      - name: bank_account_with_prefix
        regex: \b(?:kontonr\.?|kontonummer:?|bankkontonummer:?|konto:?)\s*\d{4}[.\s]?\d{2}[.\s]?\d{5}\b
        score: 0.90

  # COMPANY-registration numbers
  - name: NO_COMPANY_NUMBER_P_Recognizer
    supported_languages: [nb]
    supported_entity: NO_COMPANY_NUMBER_P
    type: custom
    patterns:
      - name: company_number_pattern
        regex: \b(?:org\.?(?:anisasjons)?nr\.?:?\s?)?\d{3}[\s]?\d{3}[\s]?\d{3}\b
        score: 0.85
      - name: company_number_with_prefix
        regex: \b(?:organisasjonsnummer|organisasjonsnr|orgnr|org\.nr\.|org\s?nr)\.?:?\s*\d{3}[\s]?\d{3}[\s]?\d{3}\b
        score: 0.90

  # LICENSE-PLATE numbers
  - name: NO_LICENSE_PLATE_P_Recognizer
    supported_languages: [nb]
    supported_entity: NO_LICENSE_PLATE_P
    type: custom
    patterns:
      - name: license_plate_pattern
        regex: \b[A-Z]{2}[\s]?\d{4,5}\b
        score: 0.85
      - name: license_plate_with_prefix
        regex: \b(?:reg\.?(?:istrerings)?nr\.?|bilnr\.?|bilskilt:?)\s*[A-Z]{2}[\s]?\d{4,5}\b
        score: 0.90

  # EMAIL
  - name: EMAIL_ADDRESS_P_Recognizer
    supported_languages: [nb]
    supported_entity: EMAIL_ADDRESS_P
    type: custom
    patterns:
      - name: email_pattern_unicode
        regex: \b[A-Za-z0-9._%+\-ÆØÅæøå]+@[A-Za-z0-9.\-ÆØÅæøå]+\.[A-Za-zÆØÅæøå]{2,}\b
        score: 0.95
      - name: email_with_prefix_unicode
        regex: \b(?:e-post|epost|mail|e-mail):?\s*[A-Za-z0-9._%+\-ÆØÅæøå]+@[A-Za-z0-9.\-ÆØÅæøå]+\.[A-Za-zÆØÅæøå]{2,}\b
        score: 0.95

  # DATE / TIME
  - name: DATE_TIME_P_Recognizer
    supported_languages: [nb]
    supported_entity: DATE_TIME_P
    type: custom
    patterns:
      - name: norwegian_date_numeric
        regex: \b(?:0?[1-9]|[12][0-9]|3[01])\.(?:0?[1-9]|1[0-2])\.\d{2,4}\b
        score: 0.60
      - name: norwegian_date_time
        regex: \b(?:0?[1-9]|[12][0-9]|3[01])\.(?:0?[1-9]|1[0-2])\.\d{2,4}\s+(?:[01]?\d|2[0-3]):[0-5]\d\b
        score: 0.70
      - name: iso_date_pattern
        regex: \b\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])\b
        score: 0.60
      - name: norwegian_text_date
        regex: \b(?:0?[1-9]|[12][0-9]|3[01])\.?\s*(?:januar|februar|mars|april|mai|juni|juli|august|september|oktober|november|desember)\s*\d{2,4}\b
        score: 0.70

  # CRYPTO addresses
  - name: CRYPTO_P_Recognizer
    supported_languages: [nb]
    supported_entity: CRYPTO_P
    type: custom
    patterns:
      - name: bitcoin_address
        regex: \b(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}\b
        score: 0.85
      - name: ethereum_address
        regex: \b0x[a-fA-F0-9]{40}\b
        score: 0.85

  # IBAN code
  - name: IBAN_CODE_P_Recognizer
    supported_languages: [nb]
    supported_entity: IBAN_CODE_P
    type: custom
    patterns:
      - name: iban_pattern
        regex: \bNO\d{2}\s?\d{4}\s?\d{4}\s?\d{3}\b
        score: 0.90

  # IP addresses
  - name: IP_ADDRESS_P_Recognizer
    supported_languages: [nb]
    supported_entity: IP_ADDRESS_P
    type: custom
    patterns:
      - name: ipv4_pattern
        regex: \b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b
        score: 0.90
      - name: ipv6_simple_pattern
        regex: \b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\b
        score: 0.90

  # URL / DOMAIN
  - name: URL_P_Recognizer
    supported_languages: [nb]
    supported_entity: URL_P
    type: custom
    patterns:
      - name: url_pattern
        regex: https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+[^\s,]
        score: 0.70
      - name: domain_pattern
        regex: \b(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]\b
        score: 0.70

  # MEDICAL-license numbers
  - name: MEDICAL_LICENSE_P_Recognizer
    supported_languages: [nb]
    supported_entity: MEDICAL_LICENSE_P
    type: custom
    patterns:
      - name: norwegian_hpr_number
        regex: \bHPR-(?:\d{7}|[A-Z0-9]{9})\b
        score: 0.90

  # spaCy Norwegian NER (built-in)
  - name: SpacyRecognizer
    supported_languages: [nb]
    type: predefined
