version: "3.9"

services:
  web:
    build: ..
    ports:
      - "8000:8000"
    environment:
      # Map  environment variables here.
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      # Optionally mount the current directory (for development).
      - .:/backend
