version: '3'
services:
  web:
    build:
      context: .         # Use current directory (i.e. backend folder)
      dockerfile: Dockerfile
    container_name: hideme-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      # This will use the GEMINI_API_KEY from the host (or from GitHub Secrets via deployment)
      GEMINI_API_KEY: ${GEMINI_API_KEY}

    # For development, you might mount the code. For production, you might remove or adjust this.
    volumes:
      - .:/Hideme_Backend/backend
      # Configure healthcheck with longer intervals to account for long processing
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/status" ]
      interval: 60s
      timeout: 20s
      retries: 3
