version: "3.9"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # This will use the GEMINI_API_KEY from your host’s environment or from GitHub Secrets (via your deployment step).
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    # Optionally, if you want to load local backup environment variables (which can be overridden by the host env)
    env_file:
      - ./backend/.env
    volumes:
      # Optional: Mount the code for development (remove or adjust for production)
      - ./backend:/Hideme_Backend/backend
