version: '3'

services:
  goapp:
    build:
      context: . # Build from the parent directory (Hideme_Backend)
      dockerfile: Dockerfile
    container_name: hideme-goapp
    restart: always
    ports:
      - "${GO_SERVER_PORT:-8080}:${GO_SERVER_PORT:-8080}"
    environment:
      - APP_ENV=${APP_ENV:-production}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-hidemedb}
      - DB_USER=${DB_USER:-hidemedba}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${GO_SERVER_PORT:-8080}
      - DB_CONNECTION_NAME=${DB_CONNECTION_NAME}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - API_KEY_ENCRYPTION_KEY=${API_KEY_ENCRYPTION_KEY}
    volumes:
      - ../gobackend/configs:/Hideme_Backend/gobackend/configs
      - goapp_logs:/var/log/hideapp


volumes:
  goapp_logs:
