name: CI/CD Pipeline

on:
  workflow_dispatch: {}
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'
      - name: Install flake8
        run: pip install flake8
      - name: Lint Python code
        run: flake8 backend

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1
      - name: Lint Go code
        run: cd gobackend && $(go env GOPATH)/bin/golangci-lint run .

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install pytest
      - name: Run Python tests
        run: pytest backend || echo "No tests found."

  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Go tests
        run: cd gobackend && go test ./...

  infra-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Validate
        run: cd Hidemeinfra && terraform init -backend=false && terraform validate
      - name: Terraform Format
        run: cd Hidemeinfra && terraform fmt -check -recursive
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Run tfsec
        run: cd Hidemeinfra && tfsec .

  deploy:
    if: github.event_name == 'pull_request'
    needs: [lint-python, lint-go, test-python, test-go, infra-check]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            cd /opt/Hideme_Backend
            git pull
            cd backend
            sudo docker compose down || true
            sudo docker compose build
            sudo docker compose up -d
            cd ../gobackend
            sudo docker compose down || true
            sudo docker compose build
            sudo docker compose up -d
